### ISSUE TITLE
Test numbers in 128-bit

### ISSUE THREAD

**Issue by Freerider689** [Freerider689/asm_project#1]
We need some numbers to test our operations.  Would be glad if you calculate some test numbers of different bit lengths in Hex and calculate their result also in Hex.

**Comment by Freerider689** [comment]
We need some numbers to test our operations.  Would be glad if you calculate some test numbers of different bit lengths in Hex and calculate their result also in Hex.

**Comment by stuckii95** [comment]
128-bit zahl
OxC3s244F571A3DAF9DD56042DBD789C72--> 1100 0011 1101 0010 0100 0100 1111 0101 0111 0001 1010 0011 1101 1010 1111 1001 1101 1101 0101 0110 0000 0100 0010 1101 1011 1101 0111 1000 1001 1100 0111 0010 

0x72C656B3FD58598ABC598EB7F4F2125C-->  0111 0010 1100 0110 0101 0110 1011 0011 1111 1101 0101 1000 0101 1001 1000 1010 1011 1100 0101 1001 1000 1110 1011 0111 1111 0100 1111 0010 0001 0010 0101 1100


64-bit zahl
OxD85FE52397525557--> 1101 1000 0101 1111 1110 0101 0010 0011 1001 0111 0101 0010 0101 0101 0101 0111

OxC7294FB73954B86E--> 1100 0111 0010 1001 0100 1111 1011 0111 0011 1001 0101 0100 1011 1000 0110 1110

32-bit Zahl
OxE45BC10B--> 1100 0100 0101 1011 1100 0001 0000 1011
Ox82AE9632 -->  1000 0010 1010 1110 1001 0110 0011 0010

16-bit Zahl 
0X75BA--> 0111 0101 1011 1010 
OxBC52--> 1011 1100 0101 0010

8-bit Zahl
0x A2 --> 1010 0010
0Xb5--> 1011 0101

**Comment by stuckii95** [comment]
[Zahlen Assebly.docx](https://github.com/Freerider689/asm_project/files/670413/Zahlen.Assebly.docx)

**Comment by stuckii95** [comment]
[Zahlen Assebly.docx](https://github.com/Freerider689/asm_project/files/670795/Zahlen.Assebly.docx)
